openapi: 3.0.1
info:
  title: Users
  version: 0.1.0
servers:
- url: "{server}:{port}/users"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /fetchUser:
    get:
      operationId: getFetchuser
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/college'
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    college:
      required:
      - address
      - name
      type: object
      properties:
        college_id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
